# author hgh
# version 1.0
import logging
import time

from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableLambda

from config.prompt_hub import PromptHub
from modules.module_services.chat_models import RobustLLM
from utils.monitor_utils.metrics import record_llm_metrics

logger = logging.getLogger(__name__)


class ProfileExtractor:
    """user profile extractor"""
    def __init__(
        self,
        llm_client: RobustLLM,
        prompt_hub: PromptHub,
        prompt_name: str = "profile_extract"
    ):
        """
        Args:
            llm_client: Low-temperature LLM client (precise extraction)
            prompt_hub: 提示词统一入口，渲染时实时取库（支持热更新）
            prompt_name: 提示词库条目名（画像抽取模板）
        """
        self.llm_client = llm_client
        self.prompt_hub = prompt_hub
        self.prompt_name = prompt_name
        self._latest_token_usage = 0

    def extract(
        self,
        conversation: str,
        known_profile: str
    ) -> str:
        """
        Call LLM to extract user profile and return the original extracted string.

        Args:
            conversation: Formatting text of recent conversations
            known_profile: Known user profile summary

        Returns:
            The extracted result string generated by LLM (in JSON array format), returns an empty array string "[]" if it fails
        """
        if not conversation or not conversation.strip():
            return ""

        try:
            total_start = time.monotonic()
            # 每次调用实时从提示词库取模板重建chain，保证热更新生效
            chain = (self.prompt_hub.as_chat_template(self.prompt_name)
                     | self.llm_client.llm
                     | RunnableLambda(self._capture_token_usage)
                     | StrOutputParser())
            extract_str = chain.invoke({
                "conversation": conversation,
                "known_profile": known_profile
            })
            record_llm_metrics(provider=self.llm_client.provider,
                               total_tokens=self._latest_token_usage,
                               duration_ms=(time.monotonic() - total_start) * 1000)
            logger.debug(f"Profile extraction raw output: {extract_str[:100]}...")
            return extract_str
        except Exception as e:
            logger.error(f"Profile extraction LLM call failed: {e}")
            return ""

    def _capture_token_usage(self, ai_message):
        # ai_message 是 LLM 返回的原始 AIMessage 对象
        if hasattr(ai_message, 'usage_metadata') and ai_message.usage_metadata:
            self._latest_token_usage = ai_message.usage_metadata.get('total_tokens', 0)
        return ai_message
