# author hgh
# version 1.0
import logging

from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from modules.module_services.chat_models import RobustLLM

logger = logging.getLogger(__name__)


class ProfileExtractor:
    """user profile extractor"""
    def __init__(
        self,
        llm_client: RobustLLM,
        extract_prompt: ChatPromptTemplate
    ):
        """
        Args:
            llm_client: Low-temperature LLM client (precise extraction)
            extract_prompt: Prompt Template for Image Extraction
        """
        self.llm_client = llm_client
        self.extract_prompt = extract_prompt
        self.chain = extract_prompt | llm_client.llm | StrOutputParser()

    def extract(
        self,
        conversation: str,
        known_profile: str
    ) -> str:
        """
        Call LLM to extract user profile and return the original extracted string.

        Args:
            conversation: Formatting text of recent conversations
            known_profile: Known user profile summary

        Returns:
            The extracted result string generated by LLM (in JSON array format), returns an empty array string "[]" if it fails
        """
        if not conversation or not conversation.strip():
            return ""

        try:
            extract_str = self.chain.invoke({
                "conversation": conversation,
                "known_profile": known_profile
            })
            logger.debug(f"Profile extraction raw output: {extract_str[:200]}...")
            return extract_str
        except Exception as e:
            logger.error(f"Profile extraction LLM call failed: {e}")
            return ""
